# Generated by Django 4.2.26 on 2025-11-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI가 생성한 설명', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='ai_description_generated_at',
            field=models.DateTimeField(blank=True, help_text='AI 설명 생성 시각', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='ai_model_version',
            field=models.CharField(blank=True, default='llama3.1:8b', help_text='사용된 AI 모델', max_length=50, null=True),
        ),
    ]
